version: "2"
services:
  database:
    image: mysql
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ROOT_PASSWORD=root

  web2:
    image: img2
    build: ./project2
    ports:
    - "1234:8000"

